spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <ihcho620@gmail.com>
    password: <oomnclqrbwpddimu>
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  application:
    name: member-service
  profiles:
    active: main
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: mysql, eureka, actuator
      profile: develop
server:
  port: 10100